services:
  # Our PostgreSQL database
    db:
      # Using  the latest PostgreSQL image
        image: postgres:latest
        ports:
          - "5432:5432"
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 12345

    # Database management interface
    adminer:
        image: adminer:latest
        ports:
            - "8081:8080"